title = "Path to Programming Blog"
baseURL = "https://www.path-to-programming.tech"
languageCode = "en-us"
theme = "ananke"
canonifyURLs = true

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 7
googleAnalytics = "UA-173532748-1"
enableRobotsTXT = true
disqusShortname = "www-path-to-programming-tech"

[params]
  favicon = "favicon.ico"
  description = ""
  facebook = ""
  twitter = "https://twitter.com/DiamanteSteven"
  instagram = ""
  youtube = ""
  github = "https://www.github.com/SDiamante13"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/steven-diamante-6a2b7782/"
  show_reading_time = true
  cover_dimming_class = "bg-black-40"
  background_color_class = "bg-mid-gray"
  featured_image = ""
  recent_posts_number = 6
  custom_css = ["css/custom.css"]